### ISSUE TITLE
love this, do you plan on offering it for python?

### ISSUE THREAD

**Issue by joshdlee** [johnf/cdk-cross-account-route53#1]
love this, do you plan on offering it for python?

**Comment by johnf** [comment]
@joshdlee I've published a python version https://pypi.org/project/cdk-cross-account-route53/0.0.3/
Would you be able to test that it works?

**Comment by joshdlee** [comment]
wasnt able to test is succesfully, I was going to try and use it to store the NS records to the parent domain hosted zone in a different account but running into troubles, looking to find a workaround

**Comment by johnf** [comment]
@joshdlee Can you share some sample code?

Also are you trying to do cross account delegation. i.e.
* Parent Zone in account A
* Child zone in account B
* You want the stack in account B to create the NS record in account A
If so you don't need my construct you can use https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_route53-readme.html#cross-account-zone-delegation

My construct is based on this but for other records

**Comment by joshdlee** [comment]
Aha! Yes that worked. So sorry, I will show your solution for non NS
records to my colleagues and see if they can find something to test

**Comment by joshdlee** [comment]
You can close my issue though!

**Comment by johnf** [comment]
Thanks
